# Generated by Django 5.0.7 on 2024-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_massages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_theme', models.CharField(default=None, max_length=100)),
                ('sending_data', models.DateTimeField(default=None)),
                ('receiving_data', models.DateTimeField(default=None)),
                ('massage_text', models.CharField(default=None, max_length=50)),
                ('files_list', models.CharField(default=None)),
            ],
        ),
    ]
